"""
Rank every UMKM in the dataset by the model's predicted success probability
and export the Top-N to src/data/top_umkm.json.

Uses the exact same logistic-regression coefficients shipped for the live
predictor (src/data/predictor_model.json), so the ranking is consistent with
the interactive "Coba Prediksi UMKM Baru" section. Output is precomputed JSON
so the dashboard stays a static, backend-free, Vercel-friendly site.

Run:
    cd scripts && python3 rank_umkm.py
"""
import csv, json, math, os

HERE = os.path.dirname(os.path.abspath(__file__))
CSV_PATH = os.path.join(HERE, "umkm_success.csv")
MODEL_PATH = os.path.join(HERE, "..", "src", "data", "predictor_model.json")
OUT_PATH = os.path.join(HERE, "..", "src", "data", "top_umkm.json")

TOP_N = 5

EDU_LABELS = {1: "SD / sederajat", 2: "SMP / sederajat", 3: "SMA / SMK",
              4: "Diploma / S1", 5: "S2 / S3"}

# practice flag -> human label (only shown when value == 1)
PRACTICE_LABELS = [
    ("Initial_Capital", "Modal Awal"),
    ("Financial_Record_Keeping", "Pembukuan Keuangan"),
    ("Internet_Usage", "Pemanfaatan Internet"),
    ("Business_Plan", "Rencana Bisnis"),
    ("Partnership", "Kemitraan"),
    ("Parent_Business_Experience", "Bisnis Keluarga"),
]

model = json.load(open(MODEL_PATH))
order = model["feature_order"]
means, stds, weights, bias = model["means"], model["stds"], model["weights"], model["bias"]
T = model["segment_thresholds"]

def sigmoid(z):
    if z < -35: return 0.0
    if z > 35: return 1.0
    return 1.0 / (1.0 + math.exp(-z))

def engineer(r):
    readiness = r["Initial_Capital"] + r["Internet_Usage"] + r["Financial_Record_Keeping"] + r["Business_Plan"]
    age_started = max(r["Age"] - r["Industry_Experience"], 0.0)
    exp_per_age = r["Industry_Experience"] / r["Age"] if r["Age"] else 0.0
    return {**r, "Readiness_Score": readiness, "Age_Started": age_started, "Exp_per_Age": exp_per_age}

def proba(fv):
    z = bias
    for j, name in enumerate(order):
        z += ((fv[name] - means[j]) / stds[j]) * weights[j]
    return sigmoid(z)

def segment(p):
    if p >= T["A"]: return "A"
    if p >= T["B"]: return "B"
    if p >= T["C"]: return "C"
    return "D"

rows = []
with open(CSV_PATH) as f:
    for i, raw in enumerate(csv.DictReader(f), start=1):
        r = {k: float(v) for k, v in raw.items()}
        fv = engineer(r)
        p = proba(fv)
        rows.append((i, r, fv, p))

# sort by probability desc, tie-break by id asc (deterministic)
rows.sort(key=lambda t: (-t[3], t[0]))

top = []
for rank, (i, r, fv, p) in enumerate(rows[:TOP_N], start=1):
    practices = [label for col, label in PRACTICE_LABELS if r[col] == 1]
    top.append({
        "rank": rank,
        "id": f"UMKM-{i:03d}",
        "probability": round(p, 4),
        "segment": segment(p),
        "success_actual": int(r["Success"]),
        "readiness_score": int(fv["Readiness_Score"]),
        "age": int(r["Age"]),
        "education": int(r["Education"]),
        "education_label": EDU_LABELS[int(r["Education"])],
        "industry_experience": int(r["Industry_Experience"]),
        "marketing_effort": int(r["Marketing_Effort"]),
        "professional_advice": int(r["Professional_Advice"]),
        "practices": practices,
    })

correct = sum(1 for t in top if t["success_actual"] == 1)
out = {
    "_comment": "Top UMKM by model-predicted success probability. Generated by scripts/rank_umkm.py "
                "from umkm_success.csv using the live predictor's logistic-regression coefficients.",
    "top": top,
    "top_n": TOP_N,
    "n_dataset": len(rows),
    "actual_success_in_top": correct,
}
json.dump(out, open(OUT_PATH, "w"), indent=2, ensure_ascii=False)

print(f"Scored {len(rows)} UMKM. Top-{TOP_N} probabilities: " + ", ".join(f"{t['probability']:.3f}" for t in top))
print(f"Of the Top-{TOP_N}, {correct} actually succeeded (Success==1) in the dataset.")
print(f"Wrote {os.path.relpath(OUT_PATH, HERE)}")
